version: "3.8"
services:
  postgres:
    image: postgres:12.1-alpine
    shm_size: 1g
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - w2018-data:/var/lib/postgresql/data

volumes:
  w2018-data:
    driver: local
